- name: install development dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "postgresql-server-dev-{{ pg_version }}"
    - git
    - make
    - gcc
